# Generated by Django 5.0.4 on 2025-01-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Shipping_full_name',
            new_name='shipping_full_name',
        ),
    ]
