# Generated by Django 5.0.4 on 2025-01-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_shipping_full_name_shippingaddress_shipping_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_full_name',
            new_name='Shipping_full_name',
        ),
    ]
