# Generated by Django 5.0.4 on 2025-01-25 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_shipping_full_name_shippingaddress_shipping_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Shipping_adress1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Shipping_adress2',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Shipping_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Shipping_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Shipping_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Shipping_full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Shipping_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Shipping_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Shipping_zipcode',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.shippingaddress'),
        ),
    ]
