# Generated by Django 5.0.4 on 2025-01-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'درانتظار پرداخت'), ('Processing', 'درحال پردازش'), ('Shipped', 'ارسال شده به پست'), ('Delivered', 'تحویل داده شده')], default='Pending', max_length=50),
        ),
    ]
