# Generated by Django 5.0.4 on 2025-01-28 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_rename_shipping_address_order_shipping_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
