# Generated by Django 5.0.4 on 2024-11-15 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stare',
            new_name='Stare',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 15, 15, 10, 41, 484831)),
        ),
    ]
