# Generated by Django 5.0.4 on 2024-11-16 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_stare_product_stare_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Stare',
            new_name='star',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 16, 10, 16, 30, 886363)),
        ),
    ]
